service: market
image: mktcode/market
servers:
  web:
    - SERVER_MARKET_APP_1_IP
    - SERVER_MARKET_APP_2_IP
registry:
  username: mktcode
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    JOB_CONCURRENCY: 3
    WEB_CONCURRENCY: 2
    DB_HOST: SERVER_MARKET_DB_IP
    # RAILS_LOG_LEVEL: debug
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "market_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
accessories:
  db:
    image: mysql:8.0
    host: SERVER_MARKET_DB_IP
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql